### ISSUE TITLE
livesplit crashes when i try to open it with this message: 

### ISSUE THREAD

**Issue by gyroscopess** [LiveSplit/LiveSplit#1068]
livesplit has crashed due to the following reason:
object reference not set to an instance of an object.

any he
![liveslipt error](https://user-images.githubusercontent.com/38815565/39398705-59f7534c-4ac6-11e8-917b-b248a4644e58.jpg)
lp?

**Comment by wooferzfg** [comment]
Could you find this error in your event logs and send it to me? https://pastebin.com/M3n52ABV

Also, which LiveSplit version are you using?

**Comment by DaGuy044** [comment]
https://gist.github.com/DaGuy044/475fa6839d92843b8c6146b800399014

is this good?

**Comment by wooferzfg** [comment]
Is there any other error in the event logs? There should be one that's similar to what was displayed in your error message.

**Comment by DaGuy044** [comment]
Log Name:      Application
Source:        LiveSplit
Date:          28/04/2018 09:25:44
Event ID:      0
Task Category: None
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      DESKTOP-AF7AO5O
Description:
Could not find file 'C:\Users\Pedro Nery\Pictures\LiveSplit_1.7.6 (1)\settings.cfg'.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at LiveSplit.View.TimerForm.LoadSettings()
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="LiveSplit" />
    <EventID Qualifiers="0">0</EventID>
    <Level>2</Level>
    <Task>0</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2018-04-28T16:25:44.009778000Z" />
    <EventRecordID>10808</EventRecordID>
    <Channel>Application</Channel>
    <Computer>DESKTOP-AF7AO5O</Computer>
    <Security />
  </System>
  <EventData>
    <Data>Could not find file 'C:\Users\Pedro Nery\Pictures\LiveSplit_1.7.6 (1)\settings.cfg'.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at LiveSplit.View.TimerForm.LoadSettings()</Data>
  </EventData>
</Event>

i think i know what it is it doesn't find one file dont know why

**Comment by wooferzfg** [comment]
That error is not a problem and happens because you don't have a settings.cfg file yet. It's not the error that caused the crash.

**Comment by DaGuy044** [comment]
ok so what do i do?

:v

**Comment by wooferzfg** [comment]
The other error should be in the event logs somewhere.

**Comment by DaGuy044** [comment]
Log Name:      Application
Source:        LiveSplit
Date:          28/04/2018 09:19:23
Event ID:      0
Task Category: None
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      DESKTOP-AF7AO5O
Description:
Object reference not set to an instance of an object.

   at LiveSplit.UI.Layout.<>c.<get_Components>b__10_0(ILayoutComponent x)
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Linq.Enumerable.Count[TSource](IEnumerable`1 source)
   at LiveSplit.View.TimerForm.SetInTimerOnlyMode()
   at LiveSplit.View.TimerForm.SetLayout(ILayout layout)
   at LiveSplit.View.TimerForm.Init(String splitsPath, String layoutPath)
   at LiveSplit.View.TimerForm..ctor(String splitsPath, String layoutPath, Boolean drawToBackBuffer, String basePath)
   at LiveSplit.Program.Main(String[] args)
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="LiveSplit" />
    <EventID Qualifiers="0">0</EventID>
    <Level>2</Level>
    <Task>0</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2018-04-28T16:19:23.869122300Z" />
    <EventRecordID>10807</EventRecordID>
    <Channel>Application</Channel>
    <Computer>DESKTOP-AF7AO5O</Computer>
    <Security />
  </System>
  <EventData>
    <Data>Object reference not set to an instance of an object.

   at LiveSplit.UI.Layout.&lt;&gt;c.&lt;get_Components&gt;b__10_0(ILayoutComponent x)
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Linq.Enumerable.Count[TSource](IEnumerable`1 source)
   at LiveSplit.View.TimerForm.SetInTimerOnlyMode()
   at LiveSplit.View.TimerForm.SetLayout(ILayout layout)
   at LiveSplit.View.TimerForm.Init(String splitsPath, String layoutPath)
   at LiveSplit.View.TimerForm..ctor(String splitsPath, String layoutPath, Boolean drawToBackBuffer, String basePath)
   at LiveSplit.Program.Main(String[] args)</Data>
  </EventData>
</Event>

i have this

**Comment by DaGuy044** [comment]
another not find settings

**Comment by DaGuy044** [comment]
Log Name:      Application
Source:        LiveSplit
Date:          28/04/2018 09:17:44
Event ID:      0
Task Category: None
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      DESKTOP-AF7AO5O
Description:
Object reference not set to an instance of an object.

   at LiveSplit.UI.Layout.<>c.<get_Components>b__10_0(ILayoutComponent x)
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Linq.Enumerable.Count[TSource](IEnumerable`1 source)
   at LiveSplit.View.TimerForm.SetInTimerOnlyMode()
   at LiveSplit.View.TimerForm.SetLayout(ILayout layout)
   at LiveSplit.View.TimerForm.Init(String splitsPath, String layoutPath)
   at LiveSplit.View.TimerForm..ctor(String splitsPath, String layoutPath, Boolean drawToBackBuffer, String basePath)
   at LiveSplit.Program.Main(String[] args)
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="LiveSplit" />
    <EventID Qualifiers="0">0</EventID>
    <Level>2</Level>
    <Task>0</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2018-04-28T16:17:44.478022500Z" />
    <EventRecordID>10805</EventRecordID>
    <Channel>Application</Channel>
    <Computer>DESKTOP-AF7AO5O</Computer>
    <Security />
  </System>
  <EventData>
    <Data>Object reference not set to an instance of an object.

   at LiveSplit.UI.Layout.&lt;&gt;c.&lt;get_Components&gt;b__10_0(ILayoutComponent x)
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Linq.Enumerable.Count[TSource](IEnumerable`1 source)
   at LiveSplit.View.TimerForm.SetInTimerOnlyMode()
   at LiveSplit.View.TimerForm.SetLayout(ILayout layout)
   at LiveSplit.View.TimerForm.Init(String splitsPath, String layoutPath)
   at LiveSplit.View.TimerForm..ctor(String splitsPath, String layoutPath, Boolean drawToBackBuffer, String basePath)
   at LiveSplit.Program.Main(String[] args)</Data>
  </EventData>
</Event>

**Comment by wooferzfg** [comment]
Alright, that's the correct error, thanks!

**Comment by DaGuy044** [comment]
![for chesus](https://user-images.githubusercontent.com/38815565/39399600-8fbfeb6a-4ad5-11e8-92e9-e1025b1c408d.jpg)

and this much of same errors

**Comment by wooferzfg** [comment]
Did you properly extract everything from LiveSplit_1.7.6.zip, including the Components folder? It's possible that the Timer component is missing.

**Comment by DaGuy044** [comment]
I didn't have to extract it don't know why it just opened

**Comment by wooferzfg** [comment]
You need to extract all the files from the zip that you downloaded before trying to open the .exe file.

**Comment by DaGuy044** [comment]
Oh thanks I'll try doing that!

**Comment by DaGuy044** [comment]
![jgjfgyjgygkygkykyg](https://user-images.githubusercontent.com/38815565/39399790-3d54362a-4ad9-11e8-9e4a-823eeb6c02ea.jpg)
why is it saying downloading from GitHub? and what does Any% means? im all new to speedrunning

**Comment by wooferzfg** [comment]
The file is hosted on GitHub (in the Releases section of this repository).

"Any%" means "any completion percentage", which is the basic "Beat the Game" category for a game.

**Comment by DaGuy044** [comment]
oh thanks!

**Comment by DaGuy044** [comment]
![iggh](https://user-images.githubusercontent.com/38815565/39399955-efe7d524-4adb-11e8-8fdd-a95e3cc2ca8b.jpg)
i had to reinstall it again but i made a little change...SE WHAT I DID THERE? HUH?

**Comment by DaGuy044** [comment]
its the 28 time i try to download it it says its getting interrupting every time

**Comment by just-ero** [comment]
Closing due to inactivity.

The issue may have been caused because the user did not extract the downloaded ZIP archive.
