### ISSUE TITLE
2 Crashes in 2 hours 

### ISSUE THREAD

**Issue by CountCreep** [LiveSplit/LiveSplit#1572]
Love this timer but I crashed 2 times during runs, timer just froze, have 6 errors in the event viewer most are the same. 

Event Viewer error around the time of crash 2 - 1.7.7 - Could not load file or assembly 'file:///H:\LiveSplit\Program\Components\Noesis.Javascript.dll' or one of its dependencies. An attempt was made to load a program with an incorrect format.

   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadFrom(String assemblyFile, Evidence securityEvidence, Byte[] hashValue, AssemblyHashAlgorithm hashAlgorithm, Boolean forIntrospection, Boolean suppressSecurityChecks, StackCrawlMark& stackMark)
   at System.Reflection.Assembly.UnsafeLoadFrom(String assemblyFile)
   at LiveSplit.UI.Components.ComponentManager.LoadFactory(String path)

**Comment by NoTeefy** [comment]
@CountCreep what game are you using it on? Are you using an autosplitter?

**Comment by just-ero** [comment]
Closing as stale.

`Noesis.Javascript` is no longer used a dependency of LiveSplit.
