### ISSUE TITLE
Livesplit won't load

### ISSUE THREAD

**Issue by Derpspace** [LiveSplit/LiveSplit#1753]
it just suddenly quit working the timer part loads and then closes right away

**Comment by Derpspace** [comment]
nvm just fixed it self for some reason

**Comment by Derpspace** [comment]
Ok Never mind that it just sometimes works and sometimes it doesn't i have tried re-downloading and such but it just wont work

**Comment by wooferzfg** [comment]
Could you send your event logs? https://pastebin.com/M3n52ABV

**Comment by kciNoisP** [comment]
I am having the same problem. This is my event log:

Could not find file 'C:\Users\Nicolas\Desktop\Livesplit\settings.cfg'. at  System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath) at  System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32  rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions  options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy,  Boolean useLongPath, Boolean checkHost) at System.IO.FileStream..ctor(String  path, FileMode mode, FileAccess access, FileShare share) at  LiveSplit.View.TimerForm.LoadSettings()
--

**Comment by wooferzfg** [comment]
That error is expected the first time that you start LiveSplit.

**Comment by kciNoisP** [comment]
I keep trying to open LiveSplit every few hours and it still gives that error. I believe this started happening after I updated LiveSplit, not sure though.

**Comment by Derpspace** [comment]
> I keep trying to open LiveSplit every few hours and it still gives that error. I believe this started happening after I updated LiveSplit, not sure though.

Yeah this never happened before 1.8 but it happens a lot now even if i use 1.7.7

Event Logs:  
at SharpDX.Result.CheckError()
   at SharpDX.DirectInput.Device.GetDeviceData(Int32 arg0, IntPtr arg1, Int32& arg2, Int32 arg3)
   at SharpDX.DirectInput.CustomDevice`3.GetBufferedData()
   at LiveSplit.Model.Input.GamepadHook.Poll()

And another One that i got was:
  at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadFrom(String assemblyFile, Evidence securityEvidence, Byte[] hashValue, AssemblyHashAlgorithm hashAlgorithm, Boolean forIntrospection, Boolean suppressSecurityChecks, StackCrawlMark& stackMark)
   at System.Reflection.Assembly.UnsafeLoadFrom(String assemblyFile)
   at LiveSplit.UI.Components.ComponentManager.LoadFactory(String path)

**Comment by wooferzfg** [comment]
Could LiveSplit not loading be an issue with your antivirus software?

**Comment by kciNoisP** [comment]
It was an issue with my antivirus software. I first tried to make an exception for LiveSplit, but that did not work. I have to completely exit out of the antivirus to allow LiveSplit to work. Not sure how to get around that.

**Comment by Derpspace** [comment]
Yeah I had to Open then close my Antivirus software to get Livesplit to work lets hope you can get around that somehow

**Comment by wooferzfg** [comment]
You should be able to whitelist LiveSplit.
