### ISSUE TITLE
When I open Livesplit, it opens for a second then closes

### ISSUE THREAD

**Issue by DarkAfro12** [LiveSplit/LiveSplit#2007]
I checked task manager and it is not running in the background. When I looked at Event Viewer this is the error i got:

Log Name:      Application
Source:        LiveSplit
Date:          8/11/2020 8:09:40 PM
Event ID:      0
Task Category: None
Level:         Error
Keywords:      Classic
User:          N/A
Description:
Root element is missing.

   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   at System.Xml.XmlLoader.Load(XmlDocument doc, XmlReader reader, Boolean preserveWhitespace)
   at System.Xml.XmlDocument.Load(XmlReader reader)
   at System.Xml.XmlDocument.Load(Stream inStream)
   at LiveSplit.Options.SettingsFactories.XMLSettingsFactory.Create()
   at LiveSplit.View.TimerForm.LoadSettings()
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="LiveSplit" />
    <EventID Qualifiers="0">0</EventID>
    <Level>2</Level>
    <Task>0</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2020-08-12T02:09:40.786795100Z" />
    <EventRecordID>26365</EventRecordID>
    <Channel>Application</Channel>
    <Computer>DESKTOP-63DDVBG</Computer>
    <Security />
  </System>
  <EventData>
    <Data>Root element is missing.

   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   at System.Xml.XmlLoader.Load(XmlDocument doc, XmlReader reader, Boolean preserveWhitespace)
   at System.Xml.XmlDocument.Load(XmlReader reader)
   at System.Xml.XmlDocument.Load(Stream inStream)
   at LiveSplit.Options.SettingsFactories.XMLSettingsFactory.Create()
   at LiveSplit.View.TimerForm.LoadSettings()</Data>
  </EventData>
</Event>

This was after I got an error saying "settings.cfg not found" and I just made a settings.cfg file myself.

**Comment by wooferzfg** [comment]
You shouldn't make a settings.cfg file yourself. That settings.cfg error is not fatal.

**Comment by just-ero** [comment]
Closing due to inactivity.

The issue was possibly caused because the user installed LiveSplit in a directory that cannot be written to without elevated rights.
