### ISSUE TITLE
LiveSplit errors when trying to read memory with autosplitter/when starting

### ISSUE THREAD

**Issue by TF4421** [LiveSplit/LiveSplit#2017]
Error when starting livesplit:

HRESULT: [0x8007001E], Module: [SharpDX.DirectInput], ApiCode:  [DIERR_INPUTLOST/InputLost], Message: The system cannot read from the specified  device. at SharpDX.Result.CheckError() at  SharpDX.DirectInput.Device.GetDeviceData(Int32 arg0, IntPtr arg1, Int32&  arg2, Int32 arg3) at SharpDX.DirectInput.CustomDevice`3.GetBufferedData() at  LiveSplit.Model.Input.GamepadHook.Poll()
--

Error when starting a run with autosplitter:

Exception thrown: 'Microsoft.CSharp.RuntimeBinder.RuntimeBinderException' in  'start' method: 'System.Dynamic.ExpandoObject' does not contain a definition for  'wasInMenu' at ASL line 87 in 'start' at  LiveSplit.ASL.ASLMethod.Call(LiveSplitState timer, ExpandoObject vars,  String& version, Double& refreshRate, Object settings, ExpandoObject  old, ExpandoObject current, Process game) at  LiveSplit.ASL.ASLScript.RunMethod(ASLMethod method, LiveSplitState state,  String& version) at LiveSplit.ASL.ASLScript.DoUpdate(LiveSplitState state)  at LiveSplit.UI.Components.ASLComponent.UpdateScript()
--

Also, even though windows documents these errors,livesplit still seems to work normally.

**Comment by TF4421** [comment]
Another two errors I found:
Only part of a ReadProcessMemory or WriteProcessMemory request was completed

   at LiveSplit.ComponentUtil.ExtensionMethods.ModulesWow64Safe(Process p)
   at LiveSplit.ComponentUtil.DeepPointer.DerefOffsets(Process process, IntPtr& ptr)
   at LiveSplit.ComponentUtil.DeepPointer.Deref[T](Process process, T& value)
   at LiveSplit.ASL.ASLState.GetValue(Process p, String type, DeepPointer pointer)
   at LiveSplit.ASL.ASLState.RefreshValues(Process p)
   at LiveSplit.ASL.ASLScript.DoInit(LiveSplitState state)
   at LiveSplit.UI.Components.ASLComponent.UpdateScript()


The handle is invalid

   at LiveSplit.ComponentUtil.ExtensionMethods.ModulesWow64Safe(Process p)
   at LiveSplit.ComponentUtil.DeepPointer.DerefOffsets(Process process, IntPtr& ptr)
   at LiveSplit.ComponentUtil.DeepPointer.Deref[T](Process process, T& value)
   at LiveSplit.ASL.ASLState.GetValue(Process p, String type, DeepPointer pointer)
   at LiveSplit.ASL.ASLState.RefreshValues(Process p)
   at LiveSplit.ASL.ASLScript.DoUpdate(LiveSplitState state)
   at LiveSplit.UI.Components.ASLComponent.UpdateScript()

**Comment by Avasam** [comment]
You probably meant `current.wasInMenu` instead of `wasInMenu` in your ASL script. It's hard to say without the script itself.

**Comment by EricSimonetti** [comment]
I'm getting the "The handle is invalid" and "The system cannot read from the specified device" errors. Did you figure out how to fix this issue?

**Comment by just-ero** [comment]
Closing due to inactivity.

The issue was likely caused due to some faulty ASL syntax.
