### ISSUE TITLE
Error Creating window handle

### ISSUE THREAD

**Issue by supermeatboy10** [LiveSplit/LiveSplit#2150]
Every few minutes or so livesplit crashes with an 'error creating window handle'. Seems to be made worse by some games/plugins but still persists after a clean install and deleting the splits/plugs that supposedly caused it. Error takes 1 of 2 forms in system logs pasted below but gives the same message. 

**Crash 1**
Error creating window handle.

   at System.Windows.Forms.NativeWindow.CreateHandle(CreateParams cp)
   at System.Windows.Forms.Control.CreateHandle()
   at System.Windows.Forms.Control.get_Handle()
   at System.Windows.Forms.Control.CreateGraphicsInternal()
   at System.Windows.Forms.ThreadExceptionDialog..ctor(Exception t)
   at System.Windows.Forms.Application.ThreadContext.OnThreadException(Exception t)
   at System.Windows.Forms.Control.WndProcException(Exception e)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
   at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   at LiveSplit.Program.Main(String[] args)

**Crash 2:** 
Error creating window handle.

   at System.Windows.Forms.NativeWindow.CreateHandle(CreateParams cp)
   at System.Windows.Forms.Timer.TimerNativeWindow.EnsureHandle()
   at System.Windows.Forms.Timer.TimerNativeWindow.StartTimer(Int32 interval)
   at System.Windows.Forms.Timer.set_Enabled(Boolean value)
   at System.Windows.Forms.ToolStripManager.ModalMenuFilter.EnterMenuModeCore()
   at System.Windows.Forms.ToolStripManager.ModalMenuFilter.SetActiveToolStripCore(ToolStrip toolStrip)
   at System.Windows.Forms.ToolStripDropDown.ReparentToActiveToolStripWindow()
   at System.Windows.Forms.ToolStripDropDown.SetVisibleCore(Boolean visible)
   at System.Windows.Forms.ToolStripDropDown.Show(Control control, Point position)
   at System.Windows.Forms.ContextMenuStrip.ShowInternal(Control source, Point location, Boolean isKeyboardActivated)
   at System.Windows.Forms.Control.WmContextMenu(Message& m, Control sourceControl)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at LiveSplit.View.TimerForm.WndProc(Message& m)

**Comment by wooferzfg** [comment]
Could you try unchecking "Allow Gamepads as Hotkeys" and see if you still have the issue?

**Comment by supermeatboy10** [comment]
> Could you try unchecking "Allow Gamepads as Hotkeys" and see if you still have the issue?

This seems to have solved the issue, thanks!
