### ISSUE TITLE
Valid LSS File Fails to Load if SRC Call Fails for Specific Game (The Legend of Zelda)

### ISSUE THREAD

**Issue by DoctorBlue** [LiveSplit/LiveSplit#2154]
Myself and another runner (on their stream) could not get our "The Legend of Zelda" split files to load. Other split files loaded fine, but this one game in particular consistently failed.

We'd either get this generic message (which I think is generated from [this line of code](https://github.com/LiveSplit/LiveSplit/blob/b893917f51245bfc5dfbc890114a32de76cfa0c8/LiveSplit/LiveSplit.View/View/TimerForm.cs#L1781)):

![image](https://user-images.githubusercontent.com/47405668/128619963-f831f2b6-2b35-461f-b7c9-9f8b862baf73.png)

or, if I launch LiveSplit by double-clicking the `lss` file in question, LiveSplit half-loads, but doesn't work (I can start/stop/reset/etc, but nothing in the UI updates; I still get prompts as if I did do the splits though, "you beat your previous times, do you want to save" etc):

![image](https://user-images.githubusercontent.com/47405668/128619979-5dd315c4-baf4-427a-9934-c5837a18ddb1.png)

I dove into the error logs, and found this (once I realized the `Game Name` being set specifically to "The Legend of Zelda" was the culprit):

    The service is too busy to handle your request. Please try again later.

    at SpeedrunComSharp.SpeedrunComClient.DoRequest(Uri uri)
    at SpeedrunComSharp.SpeedrunComClient.DoDataCollectionRequest[T](Uri uri, Func`2 parser)
    at SpeedrunComSharp.GamesClient.GetVariables(String gameId, VariablesOrdering orderBy)
    at System.Lazy`1.CreateValue()
    --- End of stack trace from previous location where exception was thrown ---
    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
    at System.Lazy`1.get_Value()
    at SpeedrunComSharp.Game.get_FullGameVariables()
    at LiveSplit.Model.RunExtensions.GetExtendedCategoryName(IRun run, Boolean showRegion, Boolean showPlatform, Boolean showVariables, Boolean waitForOnlineData)
    at LiveSplit.UI.Components.Title.Update(IInvalidator invalidator, LiveSplitState state, Single width, Single height, LayoutMode mode)
    at LiveSplit.UI.Components.ComponentRenderer.InvalidateVerticalComponent(Int32 index, LiveSplitState state, IInvalidator invalidator, Single width, Single height, Single scaleFactor)
    at LiveSplit.UI.Components.ComponentRenderer.Update(IInvalidator invalidator, LiveSplitState state, Single width, Single height, LayoutMode mode)
    at LiveSplit.View.TimerForm.<TimerElapsed>b__185_1()

**Workaround**

I managed to get around this issue by doing the following:

- Open a non-Zelda splits file (or, load a blank/new splits file)
- `Edit Splits...` and select `The Legend of Zelda` from the autocomplete dropdown

This alone allowed me to open all my other Zelda splits files without issue. My guess (knowing nothing of the codebase myself) is that dropdown/autocomplete game list flushed/created some cache, which cleared things up, and that above call to `Title.Update()` no longer happens or something.

The issue for this codebase isn't so much that SRC was busy. It's that it being busy caused LiveSplit to not function properly.

**Comment by just-ero** [comment]
Does this issue persist on the most recent stable release of LiveSplit?

**Comment by DoctorBlue** [comment]
> Does this issue persist on the most recent stable release of LiveSplit?

I've not had the issue in some time, though due to the nature of it (i.e. `"The service is too busy to handle your request. Please try again later"` leads to the wrong error message reported above), that could simply be that the API response has never been slow again.

Resolution ideally would be updating the error message to reflect the failure to contact the API, as opposed to the misleading error regarding the splits file.
