### ISSUE TITLE
my lisvesplit is crashing randomly here is the error messege

### ISSUE THREAD

**Issue by miraculousagr** [LiveSplit/LiveSplit#2158]

**Comment by miraculousagr** [comment]
Log Name:      Application
Source:        LiveSplit
Date:          8/20/2021 4:44:48 PM
Event ID:      0
Task Category: None
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      DESKTOP-G7HH5Q0
Description:
Error creating window handle.

   at System.Windows.Forms.NativeWindow.CreateHandle(CreateParams cp)
   at System.Windows.Forms.Timer.TimerNativeWindow.EnsureHandle()
   at System.Windows.Forms.Timer.TimerNativeWindow.StartTimer(Int32 interval)
   at System.Windows.Forms.Timer.set_Enabled(Boolean value)
   at System.Windows.Forms.ToolStripManager.ModalMenuFilter.EnterMenuModeCore()
   at System.Windows.Forms.ToolStripManager.ModalMenuFilter.SetActiveToolStripCore(ToolStrip toolStrip)
   at System.Windows.Forms.ToolStripDropDown.ReparentToActiveToolStripWindow()
   at System.Windows.Forms.ToolStripDropDown.SetVisibleCore(Boolean visible)
   at System.Windows.Forms.ToolStripDropDown.Show(Control control, Point position)
   at System.Windows.Forms.ContextMenuStrip.ShowInternal(Control source, Point location, Boolean isKeyboardActivated)
   at System.Windows.Forms.Control.WmContextMenu(Message& m, Control sourceControl)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at LiveSplit.View.TimerForm.WndProc(Message& m)
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="LiveSplit" />
    <EventID Qualifiers="0">0</EventID>
    <Version>0</Version>
    <Level>2</Level>
    <Task>0</Task>
    <Opcode>0</Opcode>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2021-08-20T13:44:48.1091602Z" />
    <EventRecordID>17198</EventRecordID>
    <Correlation />
    <Execution ProcessID="0" ThreadID="0" />
    <Channel>Application</Channel>
    <Computer>DESKTOP-G7HH5Q0</Computer>
    <Security />
  </System>
  <EventData>
    <Data>Error creating window handle.

   at System.Windows.Forms.NativeWindow.CreateHandle(CreateParams cp)
   at System.Windows.Forms.Timer.TimerNativeWindow.EnsureHandle()
   at System.Windows.Forms.Timer.TimerNativeWindow.StartTimer(Int32 interval)
   at System.Windows.Forms.Timer.set_Enabled(Boolean value)
   at System.Windows.Forms.ToolStripManager.ModalMenuFilter.EnterMenuModeCore()
   at System.Windows.Forms.ToolStripManager.ModalMenuFilter.SetActiveToolStripCore(ToolStrip toolStrip)
   at System.Windows.Forms.ToolStripDropDown.ReparentToActiveToolStripWindow()
   at System.Windows.Forms.ToolStripDropDown.SetVisibleCore(Boolean visible)
   at System.Windows.Forms.ToolStripDropDown.Show(Control control, Point position)
   at System.Windows.Forms.ContextMenuStrip.ShowInternal(Control source, Point location, Boolean isKeyboardActivated)
   at System.Windows.Forms.Control.WmContextMenu(Message&amp; m, Control sourceControl)
   at System.Windows.Forms.Control.WndProc(Message&amp; m)
   at System.Windows.Forms.Form.WndProc(Message&amp; m)
   at LiveSplit.View.TimerForm.WndProc(Message&amp; m)</Data>
  </EventData>
</Event>

**Comment by miraculousagr** [comment]
Log Name:      Application
Source:        LiveSplit
Date:          8/20/2021 4:33:06 PM
Event ID:      0
Task Category: None
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      DESKTOP-G7HH5Q0
Description:
Could not find file 'E:\ADMIN\Documents\LiveSplit_1.8.16\settings.cfg'.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at LiveSplit.View.TimerForm.LoadSettings()
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="LiveSplit" />
    <EventID Qualifiers="0">0</EventID>
    <Version>0</Version>
    <Level>2</Level>
    <Task>0</Task>
    <Opcode>0</Opcode>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2021-08-20T13:33:06.7951986Z" />
    <EventRecordID>17184</EventRecordID>
    <Correlation />
    <Execution ProcessID="0" ThreadID="0" />
    <Channel>Application</Channel>
    <Computer>DESKTOP-G7HH5Q0</Computer>
    <Security />
  </System>
  <EventData>
    <Data>Could not find file 'E:\ADMIN\Documents\LiveSplit_1.8.16\settings.cfg'.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at LiveSplit.View.TimerForm.LoadSettings()</Data>
  </EventData>
</Event>

**Comment by miraculousagr** [comment]
Log Name:      Application
Source:        LiveSplit
Date:          8/20/2021 4:44:48 PM
Event ID:      0
Task Category: None
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      DESKTOP-G7HH5Q0
Description:
Error creating window handle.

   at System.Windows.Forms.NativeWindow.CreateHandle(CreateParams cp)
   at System.Windows.Forms.Control.CreateHandle()
   at System.Windows.Forms.Control.get_Handle()
   at System.Windows.Forms.Control.CreateGraphicsInternal()
   at System.Windows.Forms.ThreadExceptionDialog..ctor(Exception t)
   at System.Windows.Forms.Application.ThreadContext.OnThreadException(Exception t)
   at System.Windows.Forms.Control.WndProcException(Exception e)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
   at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   at LiveSplit.Program.Main(String[] args)
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="LiveSplit" />
    <EventID Qualifiers="0">0</EventID>
    <Version>0</Version>
    <Level>2</Level>
    <Task>0</Task>
    <Opcode>0</Opcode>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2021-08-20T13:44:48.3103418Z" />
    <EventRecordID>17199</EventRecordID>
    <Correlation />
    <Execution ProcessID="0" ThreadID="0" />
    <Channel>Application</Channel>
    <Computer>DESKTOP-G7HH5Q0</Computer>
    <Security />
  </System>
  <EventData>
    <Data>Error creating window handle.

   at System.Windows.Forms.NativeWindow.CreateHandle(CreateParams cp)
   at System.Windows.Forms.Control.CreateHandle()
   at System.Windows.Forms.Control.get_Handle()
   at System.Windows.Forms.Control.CreateGraphicsInternal()
   at System.Windows.Forms.ThreadExceptionDialog..ctor(Exception t)
   at System.Windows.Forms.Application.ThreadContext.OnThreadException(Exception t)
   at System.Windows.Forms.Control.WndProcException(Exception e)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG&amp; msg)
   at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   at LiveSplit.Program.Main(String[] args)</Data>
  </EventData>
</Event>

**Comment by JCog** [comment]
I'm also having this issue, and it's preventing me from being able to use LiveSplit at all. Here's one consistent way that I've found to reproduce the issue (this is far from the only thing that's caused a crash though):

1. Close the current splits that are open
2. Go to Edit Splits, set the game to Paper Mario and the category to 100%, and click OK (probably works for any game/cat but that's what I've been trying to get to work)
3. Attempt to save the splits somewhere.

From here, sometimes I'm prevented from even opening folders, sometimes the save button doesn't work, and sometimes the save goes through successfully, but 100% of the time for me right around here, I get a crash with one of the variations posted above showing up in the Windows Event Viewer.

Also for what it's worth, I'm running Windows on version 20H2 (OS build 19042.1165).

**Comment by JCog** [comment]
I think this has to be caused by something in 1.18.16, because I've downgraded to 1.18.15 and it seems to be working correctly now. If someone decides to tackle this, I'm willing to try whatever to help out if it can't be reproduced on another machine. Also for what it's worth, I have the Counter and SpeedGuidesLive plugins installed, but I also managed to reproduce the crashes after removing their DLLs, so I'm inclined to think it's unrelated, but hard to say for sure.

**Comment by miraculousagr** [comment]
i tried 1.18.5 but it does not fix this issue thanks for replying tho

**Comment by wooferzfg** [comment]
Do you have DS4Windows installed?

**Comment by miraculousagr** [comment]
> 

no

**Comment by just-ero** [comment]
Does this issue persist on the most recent stable release of LiveSplit?
