### ISSUE TITLE
Crashing and error creating window handle

### ISSUE THREAD

**Issue by lusific** [LiveSplit/LiveSplit#2190]
Its like i said i open it, have a few minutes of use then its crashes completely or i get a error creating window handle. Is this a solvable issue?

**Comment by lusific** [comment]
![unknown](https://user-images.githubusercontent.com/54827074/144977492-150535af-b259-445e-a03d-17a5d2777c7a.png)

**Comment by lusific** [comment]
![image](https://user-images.githubusercontent.com/54827074/145160072-a4d45b7d-ee23-40bb-b5f7-c50b3e01aede.png)

**Comment by lusific** [comment]
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.ComponentModel.Win32Exception (0x80004005): Error creating window handle.
   at System.Windows.Forms.NativeWindow.CreateHandle(CreateParams cp)
   at System.Windows.Forms.Control.CreateHandle()
   at System.Windows.Forms.Control.get_Handle()
   at System.Windows.Forms.Control.CreateGraphicsInternal()
   at System.Windows.Forms.ThreadExceptionDialog..ctor(Exception t)
   at System.Windows.Forms.Application.ThreadContext.OnThreadException(Exception t)
   at System.Windows.Forms.Timer.TimerNativeWindow.OnThreadException(Exception e)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
   at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Form.ShowDialog(IWin32Window owner)
   at LiveSplit.View.TimerForm.EditLayout()
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4420.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
LiveSplit
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Speedrun/splitting/LS/LiveSplit.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4400.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4360.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4390.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
LiveSplit.Core
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Speedrun/splitting/LS/LiveSplit.Core.DLL
----------------------------------------
LiveSplit.View
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Speedrun/splitting/LS/LiveSplit.View.DLL
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4190.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4390.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
UpdateManager
    Assembly Version: 0.1.0.0
    Win32 Version: 0.1.0.0
    CodeBase: file:///C:/Speedrun/splitting/LS/UpdateManager.DLL
----------------------------------------
SpeedrunComSharp
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Speedrun/splitting/LS/SpeedrunComSharp.DLL
----------------------------------------
AxAXVLC
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Speedrun/splitting/LS/Components/AxInterop.AXVLC.dll
----------------------------------------
CefSharp.BrowserSubprocess.Core
    Assembly Version: 89.0.170.0
    Win32 Version: 89.0.170
    CodeBase: file:///C:/Speedrun/splitting/LS/Components/CefSharp.BrowserSubprocess.Core.dll
----------------------------------------
CefSharp.Core
    Assembly Version: 89.0.170.0
    Win32 Version: 89.0.170.0
    CodeBase: file:///C:/Speedrun/splitting/LS/Components/CefSharp.Core.dll
----------------------------------------
CefSharp.Core.Runtime
    Assembly Version: 89.0.170.0
    Win32 Version: 89.0.170
    CodeBase: file:///C:/Speedrun/splitting/LS/Components/CefSharp.Core.Runtime.dll
----------------------------------------
CefSharp
    Assembly Version: 89.0.170.0
    Win32 Version: 89.0.170.0
    CodeBase: file:///C:/Speedrun/splitting/LS/Components/CefSharp.dll
----------------------------------------
CefSharp.WinForms
    Assembly Version: 89.0.170.0
    Win32 Version: 89.0.170.0
    CodeBase: file:///C:/Speedrun/splitting/LS/Components/CefSharp.WinForms.dll
----------------------------------------
DarkUI
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.0.0
    CodeBase: file:///C:/Speedrun/splitting/LS/Components/DarkUI.dll
----------------------------------------
AXVLC
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Speedrun/splitting/LS/Components/Interop.AXVLC.dll
----------------------------------------
Irony
    Assembly Version: 1.1.0.0
    Win32 Version: 1.1.0
    CodeBase: file:///C:/Speedrun/splitting/LS/Components/Irony.dll
----------------------------------------
LiveSplit.BlankSpace
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Speedrun/splitting/LS/Components/LiveSplit.BlankSpace.dll
----------------------------------------
LiveSplit.CurrentComparison
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Speedrun/splitting/LS/Components/LiveSplit.CurrentComparison.dll
----------------------------------------
LiveSplit.Delta
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Speedrun/splitting/LS/Components/LiveSplit.Delta.dll
----------------------------------------
LiveSplit.DetailedTimer
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Speedrun/splitting/LS/Components/LiveSplit.DetailedTimer.dll
----------------------------------------
LiveSplit.Graph
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Speedrun/splitting/LS/Components/LiveSplit.Graph.dll
----------------------------------------
LiveSplit.HotkeyIndicator
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Speedrun/splitting/LS/Components/LiveSplit.HotkeyIndicator.dll
----------------------------------------
LiveSplit.ManualGameTime
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Speedrun/splitting/LS/Components/LiveSplit.ManualGameTime.dll
----------------------------------------
LiveSplit.PossibleTimeSave
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Speedrun/splitting/LS/Components/LiveSplit.PossibleTimeSave.dll
----------------------------------------
LiveSplit.PreviousSegment
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Speedrun/splitting/LS/Components/LiveSplit.PreviousSegment.dll
----------------------------------------
LiveSplit.Racetime
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Speedrun/splitting/LS/Components/LiveSplit.Racetime.dll
----------------------------------------
LiveSplit.RunPrediction
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Speedrun/splitting/LS/Components/LiveSplit.RunPrediction.dll
----------------------------------------
LiveSplit.ScriptableAutoSplit
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Speedrun/splitting/LS/Components/LiveSplit.ScriptableAutoSplit.dll
----------------------------------------
LiveSplit.Server
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Speedrun/splitting/LS/Components/LiveSplit.Server.dll
----------------------------------------
LiveSplit.Sound
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Speedrun/splitting/LS/Components/LiveSplit.Sound.dll
----------------------------------------
LiveSplit.Splits
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Speedrun/splitting/LS/Components/LiveSplit.Splits.dll
----------------------------------------
LiveSplit.Subsplits
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Speedrun/splitting/LS/Components/LiveSplit.Subsplits.dll
----------------------------------------
LiveSplit.SumOfBest
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Speedrun/splitting/LS/Components/LiveSplit.SumOfBest.dll
----------------------------------------
LiveSplit.Text
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Speedrun/splitting/LS/Components/LiveSplit.Text.dll
----------------------------------------
LiveSplit.Timer
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Speedrun/splitting/LS/Components/LiveSplit.Timer.dll
----------------------------------------
LiveSplit.Title
    Assembly Version: 1.0.0.1
    Win32 Version: 1.0.0.1
    CodeBase: file:///C:/Speedrun/splitting/LS/Components/LiveSplit.Title.dll
----------------------------------------
LiveSplit.TotalPlaytime
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Speedrun/splitting/LS/Components/LiveSplit.TotalPlaytime.dll
----------------------------------------
LiveSplit.Video
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Speedrun/splitting/LS/Components/LiveSplit.Video.dll
----------------------------------------
LiveSplit.WorldRecord
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Speedrun/splitting/LS/Components/LiveSplit.WorldRecord.dll
----------------------------------------
NAudio
    Assembly Version: 1.7.3.0
    Win32 Version: 1.7.3.0
    CodeBase: file:///C:/Speedrun/splitting/LS/Components/NAudio.dll
----------------------------------------
Microsoft.CSharp
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Microsoft.CSharp/v4.0_4.0.0.0__b03f5f7f11d50a3a/Microsoft.CSharp.dll
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------
System.Web.Extensions
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4330.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Web.Extensions/v4.0_4.0.0.0__31bf3856ad364e35/System.Web.Extensions.dll
----------------------------------------
System.Web
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4330.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/System.Web/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Web.dll
----------------------------------------
System.Dynamic
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Dynamic/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Dynamic.dll
----------------------------------------
Anonymously Hosted DynamicMethods Assembly
    Assembly Version: 0.0.0.0
    Win32 Version: 4.8.4420.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/mscorlib/v4.0_4.0.0.0__b77a5c561934e089/mscorlib.dll
----------------------------------------
WindowsBase
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4390.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/WindowsBase/v4.0_4.0.0.0__31bf3856ad364e35/WindowsBase.dll
----------------------------------------
SharpDX.DirectInput
    Assembly Version: 2.5.0.0
    Win32 Version: 2.5.0
    CodeBase: file:///C:/Speedrun/splitting/LS/SharpDX.DirectInput.DLL
----------------------------------------
SharpDX
    Assembly Version: 2.5.0.0
    Win32 Version: 2.5.0
    CodeBase: file:///C:/Speedrun/splitting/LS/SharpDX.DLL
----------------------------------------
Microsoft.WindowsAPICodePack.Shell
    Assembly Version: 1.1.0.0
    Win32 Version: 1.1.0.0
    CodeBase: file:///C:/Speedrun/splitting/LS/Microsoft.WindowsAPICodePack.Shell.DLL
----------------------------------------
Microsoft.WindowsAPICodePack
    Assembly Version: 1.1.0.0
    Win32 Version: 1.1.0.0
    CodeBase: file:///C:/Speedrun/splitting/LS/Microsoft.WindowsAPICodePack.DLL
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

**Comment by wooferzfg** [comment]
Do you have DS4Windows installed?

**Comment by lusific** [comment]
> 

yeah i use it for my ps4 controller, do they have issues with each other?

**Comment by wooferzfg** [comment]
Potentially yes: https://github.com/LiveSplit/LiveSplit/issues/2146

**Comment by ashifhusainoo7** [comment]
> See the end of this message for details on invoking just-in-time (JIT) debugging instead of this dialog box.
> 
> ************** Exception Text ************** System.ComponentModel.Win32Exception (0x80004005): Error creating window handle. at System.Windows.Forms.NativeWindow.CreateHandle(CreateParams cp) at System.Windows.Forms.Control.CreateHandle() at System.Windows.Forms.Control.get_Handle() at System.Windows.Forms.Control.CreateGraphicsInternal() at System.Windows.Forms.ThreadExceptionDialog..ctor(Exception t) at System.Windows.Forms.Application.ThreadContext.OnThreadException(Exception t) at System.Windows.Forms.Timer.TimerNativeWindow.OnThreadException(Exception e) at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam) at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg) at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData) at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context) at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context) at System.Windows.Forms.Form.ShowDialog(IWin32Window owner) at LiveSplit.View.TimerForm.EditLayout() at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e) at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e) at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e) at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e) at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea) at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea) at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks) at System.Windows.Forms.Control.WndProc(Message& m) at System.Windows.Forms.ToolStrip.WndProc(Message& m) at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m) at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
> 
> ## ************** Loaded Assemblies **************
> mscorlib
> Assembly Version: 4.0.0.0
> Win32 Version: 4.8.4420.0 built by: NET48REL1LAST_C
> CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
> ## LiveSplit
> Assembly Version: 1.0.0.0
> Win32 Version: 1.0.0.0
> CodeBase: file:///C:/Speedrun/splitting/LS/LiveSplit.exe
> ## System.Windows.Forms
> Assembly Version: 4.0.0.0
> Win32 Version: 4.8.4400.0 built by: NET48REL1LAST_C
> CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
> ## System
> Assembly Version: 4.0.0.0
> Win32 Version: 4.8.4360.0 built by: NET48REL1LAST_C
> CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
> ## System.Drawing
> Assembly Version: 4.0.0.0
> Win32 Version: 4.8.4390.0 built by: NET48REL1LAST_C
> CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
> ## LiveSplit.Core
> Assembly Version: 1.0.0.0
> Win32 Version: 1.0.0.0
> CodeBase: file:///C:/Speedrun/splitting/LS/LiveSplit.Core.DLL
> ## LiveSplit.View
> Assembly Version: 1.0.0.0
> Win32 Version: 1.0.0.0
> CodeBase: file:///C:/Speedrun/splitting/LS/LiveSplit.View.DLL
> ## System.Configuration
> Assembly Version: 4.0.0.0
> Win32 Version: 4.8.4190.0 built by: NET48REL1LAST_B
> CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
> ## System.Core
> Assembly Version: 4.0.0.0
> Win32 Version: 4.8.4390.0 built by: NET48REL1LAST_C
> CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
> ## System.Xml
> Assembly Version: 4.0.0.0
> Win32 Version: 4.8.4084.0 built by: NET48REL1
> CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
> ## UpdateManager
> Assembly Version: 0.1.0.0
> Win32 Version: 0.1.0.0
> CodeBase: file:///C:/Speedrun/splitting/LS/UpdateManager.DLL
> ## SpeedrunComSharp
> Assembly Version: 1.0.0.0
> Win32 Version: 1.0.0.0
> CodeBase: file:///C:/Speedrun/splitting/LS/SpeedrunComSharp.DLL
> ## AxAXVLC
> Assembly Version: 1.0.0.0
> Win32 Version: 1.0.0.0
> CodeBase: file:///C:/Speedrun/splitting/LS/Components/AxInterop.AXVLC.dll
> ## CefSharp.BrowserSubprocess.Core
> Assembly Version: 89.0.170.0
> Win32 Version: 89.0.170
> CodeBase: file:///C:/Speedrun/splitting/LS/Components/CefSharp.BrowserSubprocess.Core.dll
> ## CefSharp.Core
> Assembly Version: 89.0.170.0
> Win32 Version: 89.0.170.0
> CodeBase: file:///C:/Speedrun/splitting/LS/Components/CefSharp.Core.dll
> ## CefSharp.Core.Runtime
> Assembly Version: 89.0.170.0
> Win32 Version: 89.0.170
> CodeBase: file:///C:/Speedrun/splitting/LS/Components/CefSharp.Core.Runtime.dll
> ## CefSharp
> Assembly Version: 89.0.170.0
> Win32 Version: 89.0.170.0
> CodeBase: file:///C:/Speedrun/splitting/LS/Components/CefSharp.dll
> ## CefSharp.WinForms
> Assembly Version: 89.0.170.0
> Win32 Version: 89.0.170.0
> CodeBase: file:///C:/Speedrun/splitting/LS/Components/CefSharp.WinForms.dll
> ## DarkUI
> Assembly Version: 2.0.0.0
> Win32 Version: 2.0.0.0
> CodeBase: file:///C:/Speedrun/splitting/LS/Components/DarkUI.dll
> ## AXVLC
> Assembly Version: 1.0.0.0
> Win32 Version: 1.0.0.0
> CodeBase: file:///C:/Speedrun/splitting/LS/Components/Interop.AXVLC.dll
> ## Irony
> Assembly Version: 1.1.0.0
> Win32 Version: 1.1.0
> CodeBase: file:///C:/Speedrun/splitting/LS/Components/Irony.dll
> ## LiveSplit.BlankSpace
> Assembly Version: 1.0.0.0
> Win32 Version: 1.0.0.0
> CodeBase: file:///C:/Speedrun/splitting/LS/Components/LiveSplit.BlankSpace.dll
> ## LiveSplit.CurrentComparison
> Assembly Version: 1.0.0.0
> Win32 Version: 1.0.0.0
> CodeBase: file:///C:/Speedrun/splitting/LS/Components/LiveSplit.CurrentComparison.dll
> ## LiveSplit.Delta
> Assembly Version: 1.0.0.0
> Win32 Version: 1.0.0.0
> CodeBase: file:///C:/Speedrun/splitting/LS/Components/LiveSplit.Delta.dll
> ## LiveSplit.DetailedTimer
> Assembly Version: 1.0.0.0
> Win32 Version: 1.0.0.0
> CodeBase: file:///C:/Speedrun/splitting/LS/Components/LiveSplit.DetailedTimer.dll
> ## LiveSplit.Graph
> Assembly Version: 1.0.0.0
> Win32 Version: 1.0.0.0
> CodeBase: file:///C:/Speedrun/splitting/LS/Components/LiveSplit.Graph.dll
> ## LiveSplit.HotkeyIndicator
> Assembly Version: 1.0.0.0
> Win32 Version: 1.0.0.0
> CodeBase: file:///C:/Speedrun/splitting/LS/Components/LiveSplit.HotkeyIndicator.dll
> ## LiveSplit.ManualGameTime
> Assembly Version: 1.0.0.0
> Win32 Version: 1.0.0.0
> CodeBase: file:///C:/Speedrun/splitting/LS/Components/LiveSplit.ManualGameTime.dll
> ## LiveSplit.PossibleTimeSave
> Assembly Version: 1.0.0.0
> Win32 Version: 1.0.0.0
> CodeBase: file:///C:/Speedrun/splitting/LS/Components/LiveSplit.PossibleTimeSave.dll
> ## LiveSplit.PreviousSegment
> Assembly Version: 1.0.0.0
> Win32 Version: 1.0.0.0
> CodeBase: file:///C:/Speedrun/splitting/LS/Components/LiveSplit.PreviousSegment.dll
> ## LiveSplit.Racetime
> Assembly Version: 1.0.0.0
> Win32 Version: 1.0.0.0
> CodeBase: file:///C:/Speedrun/splitting/LS/Components/LiveSplit.Racetime.dll
> ## LiveSplit.RunPrediction
> Assembly Version: 1.0.0.0
> Win32 Version: 1.0.0.0
> CodeBase: file:///C:/Speedrun/splitting/LS/Components/LiveSplit.RunPrediction.dll
> ## LiveSplit.ScriptableAutoSplit
> Assembly Version: 1.0.0.0
> Win32 Version: 1.0.0.0
> CodeBase: file:///C:/Speedrun/splitting/LS/Components/LiveSplit.ScriptableAutoSplit.dll
> ## LiveSplit.Server
> Assembly Version: 1.0.0.0
> Win32 Version: 1.0.0.0
> CodeBase: file:///C:/Speedrun/splitting/LS/Components/LiveSplit.Server.dll
> ## LiveSplit.Sound
> Assembly Version: 1.0.0.0
> Win32 Version: 1.0.0.0
> CodeBase: file:///C:/Speedrun/splitting/LS/Components/LiveSplit.Sound.dll
> ## LiveSplit.Splits
> Assembly Version: 1.0.0.0
> Win32 Version: 1.0.0.0
> CodeBase: file:///C:/Speedrun/splitting/LS/Components/LiveSplit.Splits.dll
> ## LiveSplit.Subsplits
> Assembly Version: 1.0.0.0
> Win32 Version: 1.0.0.0
> CodeBase: file:///C:/Speedrun/splitting/LS/Components/LiveSplit.Subsplits.dll
> ## LiveSplit.SumOfBest
> Assembly Version: 1.0.0.0
> Win32 Version: 1.0.0.0
> CodeBase: file:///C:/Speedrun/splitting/LS/Components/LiveSplit.SumOfBest.dll
> ## LiveSplit.Text
> Assembly Version: 1.0.0.0
> Win32 Version: 1.0.0.0
> CodeBase: file:///C:/Speedrun/splitting/LS/Components/LiveSplit.Text.dll
> ## LiveSplit.Timer
> Assembly Version: 1.0.0.0
> Win32 Version: 1.0.0.0
> CodeBase: file:///C:/Speedrun/splitting/LS/Components/LiveSplit.Timer.dll
> ## LiveSplit.Title
> Assembly Version: 1.0.0.1
> Win32 Version: 1.0.0.1
> CodeBase: file:///C:/Speedrun/splitting/LS/Components/LiveSplit.Title.dll
> ## LiveSplit.TotalPlaytime
> Assembly Version: 1.0.0.0
> Win32 Version: 1.0.0.0
> CodeBase: file:///C:/Speedrun/splitting/LS/Components/LiveSplit.TotalPlaytime.dll
> ## LiveSplit.Video
> Assembly Version: 1.0.0.0
> Win32 Version: 1.0.0.0
> CodeBase: file:///C:/Speedrun/splitting/LS/Components/LiveSplit.Video.dll
> ## LiveSplit.WorldRecord
> Assembly Version: 1.0.0.0
> Win32 Version: 1.0.0.0
> CodeBase: file:///C:/Speedrun/splitting/LS/Components/LiveSplit.WorldRecord.dll
> ## NAudio
> Assembly Version: 1.7.3.0
> Win32 Version: 1.7.3.0
> CodeBase: file:///C:/Speedrun/splitting/LS/Components/NAudio.dll
> ## Microsoft.CSharp
> Assembly Version: 4.0.0.0
> Win32 Version: 4.8.4084.0
> CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Microsoft.CSharp/v4.0_4.0.0.0__b03f5f7f11d50a3a/Microsoft.CSharp.dll
> ## Accessibility
> Assembly Version: 4.0.0.0
> Win32 Version: 4.8.4084.0 built by: NET48REL1
> CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
> ## System.Web.Extensions
> Assembly Version: 4.0.0.0
> Win32 Version: 4.8.4330.0
> CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Web.Extensions/v4.0_4.0.0.0__31bf3856ad364e35/System.Web.Extensions.dll
> ## System.Web
> Assembly Version: 4.0.0.0
> Win32 Version: 4.8.4330.0 built by: NET48REL1LAST_B
> CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/System.Web/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Web.dll
> ## System.Dynamic
> Assembly Version: 4.0.0.0
> Win32 Version: 4.8.4084.0
> CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Dynamic/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Dynamic.dll
> ## Anonymously Hosted DynamicMethods Assembly
> Assembly Version: 0.0.0.0
> Win32 Version: 4.8.4420.0 built by: NET48REL1LAST_C
> CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/mscorlib/v4.0_4.0.0.0__b77a5c561934e089/mscorlib.dll
> ## WindowsBase
> Assembly Version: 4.0.0.0
> Win32 Version: 4.8.4390.0 built by: NET48REL1LAST_C
> CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/WindowsBase/v4.0_4.0.0.0__31bf3856ad364e35/WindowsBase.dll
> ## SharpDX.DirectInput
> Assembly Version: 2.5.0.0
> Win32 Version: 2.5.0
> CodeBase: file:///C:/Speedrun/splitting/LS/SharpDX.DirectInput.DLL
> ## SharpDX
> Assembly Version: 2.5.0.0
> Win32 Version: 2.5.0
> CodeBase: file:///C:/Speedrun/splitting/LS/SharpDX.DLL
> ## Microsoft.WindowsAPICodePack.Shell
> Assembly Version: 1.1.0.0
> Win32 Version: 1.1.0.0
> CodeBase: file:///C:/Speedrun/splitting/LS/Microsoft.WindowsAPICodePack.Shell.DLL
> ## Microsoft.WindowsAPICodePack
> Assembly Version: 1.1.0.0
> Win32 Version: 1.1.0.0
> CodeBase: file:///C:/Speedrun/splitting/LS/Microsoft.WindowsAPICodePack.DLL
> ************** JIT Debugging ************** To enable just-in-time (JIT) debugging, the .config file for this application or computer (machine.config) must have the jitDebugging value set in the system.windows.forms section. The application must also be compiled with debugging enabled.
> 
> For example:
> 
> When JIT debugging is enabled, any unhandled exception will be sent to the JIT debugger registered on the computer rather than be handled by this dialog box.

Hey i am also getting the same error for one of my WinForms application, will one of you please guide me on how to solve it if someone got the answers.

**Comment by ashifhusainoo7** [comment]
Hey I am also getting the same issue for one of my ,Winform Applications. if someone got the solution please let me know how can i solve it.
