### ISSUE TITLE
Livesplit causing lag/stuttering when autospiltter is on - even when timer is not running. 

### ISSUE THREAD

**Issue by TheRewinderCC** [LiveSplit/LiveSplit#2261]
Hey everyone, 

I'm having a frustrating issue at the moment with LiveSplit where - when the autosplitter is **activated** - it lags and stutters; it becomes **less responsive** and **slow**. 

At first, I thought this issue was **not** related to the autosplitter function at all, and just thought that LiveSplit was becoming slow and stuttery for **no reason** at all.

However, once I decided to **deactivate** the autosplitter, it stopped lagging and stuttering instantly. When I **reactivated** the autosplitter however, the lag and stutter **came back**.

What's even stranger about this issue is that even when the autosplitter is **noteven being used** , the lag and stutter **remains**; it only goes away once **deactivated**.

Another thing to note as well, as the timer runs, the stutter and lag **progressively** gets **worse** and **worse**, to the point of the sound effects (e.g. reset sound, PB sound) sounding choppy and very slow.

I went to the event viewer to see if I could find any errors related to LiveSplit, and unsurprisingly, there were many, **MANY**, errors. 

![image](https://user-images.githubusercontent.com/65027375/175825833-08c3e3aa-f1e2-4a9e-9984-d7c37a852e71.png)

### A lot of these errors stated the **same** thing:

```
Access is denied

   at System.Diagnostics.ProcessManager.OpenProcess(Int32 processId, Int32 access, Boolean throwIfExited)
   at System.Diagnostics.Process.GetProcessHandle(Int32 access, Boolean throwIfExited)
   at System.Diagnostics.Process.GetProcessTimes()
   at System.Diagnostics.Process.get_StartTime()
   at System.Linq.EnumerableSorter`2.ComputeKeys(TElement[] elements, Int32 count)
   at System.Linq.EnumerableSorter`1.Sort(TElement[] elements, Int32 count)
   at System.Linq.OrderedEnumerable`1.<GetEnumerator>d__1.MoveNext()
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at LiveSplit.ASL.ASLScript.<TryConnect>b__40_0(String proccessName)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at LiveSplit.ASL.ASLScript.TryConnect(LiveSplitState state)
   at LiveSplit.UI.Components.ASLComponent.UpdateScript()
```

### Some errors stated this (and is perhaps unrelated to the issue but will share anyway):

```
The handle is invalid

   at LiveSplit.ComponentUtil.ExtensionMethods.ModulesWow64Safe(Process p)
   at LiveSplit.ComponentUtil.DeepPointer.DerefOffsets(Process process, IntPtr& ptr)
   at LiveSplit.ComponentUtil.DeepPointer.Deref[T](Process process, T& value)
   at LiveSplit.ASL.ASLState.GetValue(Process p, String type, DeepPointer pointer)
   at LiveSplit.ASL.ASLState.RefreshValues(Process p)
   at LiveSplit.ASL.ASLScript.DoUpdate(LiveSplitState state)
   at LiveSplit.UI.Components.ASLComponent.UpdateScript()
```

```
Only part of a ReadProcessMemory or WriteProcessMemory request was completed

   at LiveSplit.ComponentUtil.ExtensionMethods.ModulesWow64Safe(Process p)
   at LiveSplit.ComponentUtil.DeepPointer.DerefOffsets(Process process, IntPtr& ptr)
   at LiveSplit.ComponentUtil.DeepPointer.Deref[T](Process process, T& value)
   at LiveSplit.ASL.ASLState.GetValue(Process p, String type, DeepPointer pointer)
   at LiveSplit.ASL.ASLState.RefreshValues(Process p)
   at LiveSplit.ASL.ASLScript.DoInit(LiveSplitState state)
   at LiveSplit.UI.Components.ASLComponent.UpdateScript()
```

I don't know how **unique** this issue is, but from what I've researched, I can't really find anything **similar** to the issue that I'm having. 

I already tried reinstalling, and I even tried rolling back my graphics drivers - however, to **no avail.**

I'd really appreciate help on understanding this so I can fix it - and because I really just want to get runs done and to have a good time without inconveniences like this. 

Thanks.

**Comment by wooferzfg** [comment]
This is an issue with whatever Auto Splitter you're using. Please report this to the developer of that Auto Splitter.

**Comment by TheRewinderCC** [comment]
This is really strange. I've used the same autosplitters in the past and have never had any issues like this - and if I recall correctly they haven't been updated. 

Additionally, it seems that I'm the only one experiencing the issues regarding lag and stutter and everyone else's works fine.

Thanks for the response.
