### ISSUE TITLE
Error when right-clicking at negative screen coordinates

### ISSUE THREAD

**Issue by StevenH237** [LiveSplit/LiveSplit#2328]
I have a three screen layout on my PC, but one of the screens is located above the main screen, which results in all y-coordinates on that screen being negative. Right-clicking LiveSplit anywhere on that screen results in the error "Arithmetic operation resulted in an overflow.". If LiveSplit is split across the top and a non-top screen, only the portion on the top screen is affected.

Full error details:

```
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.OverflowException: Arithmetic operation resulted in an overflow.
   at LiveSplit.View.TimerForm.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4614.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
LiveSplit
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/Nixill/Programs/LiveSplit/LiveSplit.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4550.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4605.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4390.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
LiveSplit.Core
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/Nixill/Programs/LiveSplit/LiveSplit.Core.DLL
----------------------------------------
LiveSplit.View
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/Nixill/Programs/LiveSplit/LiveSplit.View.DLL
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4190.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4605.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
UpdateManager
    Assembly Version: 0.1.0.0
    Win32 Version: 0.1.0.0
    CodeBase: file:///C:/Users/Nixill/Programs/LiveSplit/UpdateManager.DLL
----------------------------------------
SpeedrunComSharp
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/Nixill/Programs/LiveSplit/SpeedrunComSharp.DLL
----------------------------------------
AxAXVLC
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/Nixill/Programs/LiveSplit/Components/AxInterop.AXVLC.dll
----------------------------------------
DarkUI
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.0.0
    CodeBase: file:///C:/Users/Nixill/Programs/LiveSplit/Components/DarkUI.dll
----------------------------------------
AXVLC
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/Nixill/Programs/LiveSplit/Components/Interop.AXVLC.dll
----------------------------------------
Irony
    Assembly Version: 1.1.0.0
    Win32 Version: 1.1.0
    CodeBase: file:///C:/Users/Nixill/Programs/LiveSplit/Components/Irony.dll
----------------------------------------
LiveSplit.AutoSplittingRuntime
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/Nixill/Programs/LiveSplit/Components/LiveSplit.AutoSplittingRuntime.dll
----------------------------------------
LiveSplit.BlankSpace
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/Nixill/Programs/LiveSplit/Components/LiveSplit.BlankSpace.dll
----------------------------------------
LiveSplit.CurrentComparison
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/Nixill/Programs/LiveSplit/Components/LiveSplit.CurrentComparison.dll
----------------------------------------
LiveSplit.Delta
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/Nixill/Programs/LiveSplit/Components/LiveSplit.Delta.dll
----------------------------------------
LiveSplit.DetailedTimer
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/Nixill/Programs/LiveSplit/Components/LiveSplit.DetailedTimer.dll
----------------------------------------
LiveSplit.Graph
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/Nixill/Programs/LiveSplit/Components/LiveSplit.Graph.dll
----------------------------------------
LiveSplit.HotkeyIndicator
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/Nixill/Programs/LiveSplit/Components/LiveSplit.HotkeyIndicator.dll
----------------------------------------
LiveSplit.ManualGameTime
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/Nixill/Programs/LiveSplit/Components/LiveSplit.ManualGameTime.dll
----------------------------------------
LiveSplit.PossibleTimeSave
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/Nixill/Programs/LiveSplit/Components/LiveSplit.PossibleTimeSave.dll
----------------------------------------
LiveSplit.PreviousSegment
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/Nixill/Programs/LiveSplit/Components/LiveSplit.PreviousSegment.dll
----------------------------------------
LiveSplit.Racetime
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/Nixill/Programs/LiveSplit/Components/LiveSplit.Racetime.dll
----------------------------------------
LiveSplit.RunPrediction
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/Nixill/Programs/LiveSplit/Components/LiveSplit.RunPrediction.dll
----------------------------------------
LiveSplit.ScriptableAutoSplit
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/Nixill/Programs/LiveSplit/Components/LiveSplit.ScriptableAutoSplit.dll
----------------------------------------
LiveSplit.Sound
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/Nixill/Programs/LiveSplit/Components/LiveSplit.Sound.dll
----------------------------------------
LiveSplit.Splits
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/Nixill/Programs/LiveSplit/Components/LiveSplit.Splits.dll
----------------------------------------
LiveSplit.Subsplits
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/Nixill/Programs/LiveSplit/Components/LiveSplit.Subsplits.dll
----------------------------------------
LiveSplit.SumOfBest
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/Nixill/Programs/LiveSplit/Components/LiveSplit.SumOfBest.dll
----------------------------------------
LiveSplit.Text
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/Nixill/Programs/LiveSplit/Components/LiveSplit.Text.dll
----------------------------------------
LiveSplit.Timer
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/Nixill/Programs/LiveSplit/Components/LiveSplit.Timer.dll
----------------------------------------
LiveSplit.Title
    Assembly Version: 1.0.0.1
    Win32 Version: 1.0.0.1
    CodeBase: file:///C:/Users/Nixill/Programs/LiveSplit/Components/LiveSplit.Title.dll
----------------------------------------
LiveSplit.TotalPlaytime
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/Nixill/Programs/LiveSplit/Components/LiveSplit.TotalPlaytime.dll
----------------------------------------
LiveSplit.Video
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/Nixill/Programs/LiveSplit/Components/LiveSplit.Video.dll
----------------------------------------
LiveSplit.WorldRecord
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/Nixill/Programs/LiveSplit/Components/LiveSplit.WorldRecord.dll
----------------------------------------
NAudio
    Assembly Version: 1.7.3.0
    Win32 Version: 1.7.3.0
    CodeBase: file:///C:/Users/Nixill/Programs/LiveSplit/Components/NAudio.dll
----------------------------------------
Microsoft.CSharp
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Microsoft.CSharp/v4.0_4.0.0.0__b03f5f7f11d50a3a/Microsoft.CSharp.dll
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------
System.Web.Extensions
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4494.0
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Web.Extensions/v4.0_4.0.0.0__31bf3856ad364e35/System.Web.Extensions.dll
----------------------------------------
System.Web
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4494.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_64/System.Web/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Web.dll
----------------------------------------
System.Dynamic
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Dynamic/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Dynamic.dll
----------------------------------------
Anonymously Hosted DynamicMethods Assembly
    Assembly Version: 0.0.0.0
    Win32 Version: 4.8.4614.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_64/mscorlib/v4.0_4.0.0.0__b77a5c561934e089/mscorlib.dll
----------------------------------------
WindowsBase
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4605.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/WindowsBase/v4.0_4.0.0.0__31bf3856ad364e35/WindowsBase.dll
----------------------------------------
Microsoft.WindowsAPICodePack.Shell
    Assembly Version: 1.1.0.0
    Win32 Version: 1.1.0.0
    CodeBase: file:///C:/Users/Nixill/Programs/LiveSplit/Microsoft.WindowsAPICodePack.Shell.DLL
----------------------------------------
Microsoft.WindowsAPICodePack
    Assembly Version: 1.1.0.0
    Win32 Version: 1.1.0.0
    CodeBase: file:///C:/Users/Nixill/Programs/LiveSplit/Microsoft.WindowsAPICodePack.DLL
----------------------------------------
magwu3o3
    Assembly Version: 0.0.0.0
    Win32 Version: 4.8.4605.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
gfweudtq
    Assembly Version: 0.0.0.0
    Win32 Version: 4.8.4605.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
vnb55jo0
    Assembly Version: 0.0.0.0
    Win32 Version: 4.8.4605.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
knzyo5ml
    Assembly Version: 0.0.0.0
    Win32 Version: 4.8.4605.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
s2eybtwv
    Assembly Version: 0.0.0.0
    Win32 Version: 4.8.4605.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
apyly1nj
    Assembly Version: 0.0.0.0
    Win32 Version: 4.8.4605.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.
```

**Comment by wooferzfg** [comment]
Strange - my monitors are arranged similarly, yet this bug doesn't happen for me.

**Comment by wooferzfg** [comment]
What version of Windows are you using?

**Comment by adamreiswig** [comment]
> What version of Windows are you using?

Windows 10 Pro. 10.0.19045

**Comment by just-ero** [comment]
Does this issue persist? Can you share more about your setup? The actual coordinates? Proof that it does work fine if not clicked at a negative coordinate? A video could work.

**Comment by StevenH237** [comment]
[Here's a video.](https://www.youtube.com/watch?v=1_lwiXOOE1Q)

**Comment by wooferzfg** [comment]
I'm still not able to reproduce this, even with an identical monitor setup. If I had to guess, the issue comes up on this line: https://github.com/LiveSplit/LiveSplit/blob/f1bffb6c6919b74a780e3e33203ae71512826995/src/LiveSplit.View/View/TimerForm.cs#L1546

**Comment by wooferzfg** [comment]
@StevenH237 Do you have a 64 bit PC?

**Comment by StevenH237** [comment]
I do. I wonder if it's tied to a specific component on the current layout.

**Comment by wooferzfg** [comment]
@StevenH237 Could you send me your layout file?

**Comment by StevenH237** [comment]
Got it here: https://gist.github.com/StevenH237/10fdce34add885fede0b92a5bcdb4fb1

I also included the "Scriptable Auto Splitter" that I'm using just in case that changes anything.

**Comment by wooferzfg** [comment]
I'm not able to reproduce this, even with your layout. I can't really make progress on this issue with the current information I have.

@StevenH237 Would you be able to compile LiveSplit and determine:
1) what line the error occurs on
2) if it's [this line](https://github.com/LiveSplit/LiveSplit/blob/f1bffb6c6919b74a780e3e33203ae71512826995/src/LiveSplit.View/View/TimerForm.cs#L1546), what the value of `m.LParam` is here?

**Comment by StevenH237** [comment]
Not for a few days, and I may need help as I do - but, in theory, that's something I can do, yes.

**Comment by wooferzfg** [comment]
Feel free to add me on Discord - my username is @wooferzfg
