### ISSUE TITLE
Racetime error after auto update

### ISSUE THREAD

**Issue by SophieFitz** [LiveSplit/LiveSplit#2496]
I just auto-updated livesplit and now I get an error on every startup. 

This is the Event Viewer log entry:

```
Method 'GetGameImage' in type 'LiveSplit.Racetime.RacetimeAPI' from assembly 'LiveSplit.Racetime, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.

   at LiveSplit.Racetime.RacetimeFactory.Create(ITimerModel model, RaceProviderSettings settings)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.<ReverseIterator>d__75`1.MoveNext()
   at LiveSplit.View.TimerForm.UpdateRaceProviderIntegration()
   at LiveSplit.View.TimerForm.Init(String splitsPath, String layoutPath)
   at LiveSplit.Program.Main(String[] args)
```

**Comment by wooferzfg** [comment]
Please re-download LiveSplit. `GetGameImage` was removed from the Racetime integration, so it looks like one of the DLLs in your LiveSplit folder is outdated.

**Comment by SophieFitz** [comment]
If I may, auto-update should have fixed this automatically.

**Comment by wooferzfg** [comment]
I tried updating from both LiveSplit 1.8.15 and LiveSplit 1.8.28 and both worked correctly, so I wasn't able to reproduce your issue. I'm not sure what state your LiveSplit folder was in, or which build you originally downloaded.

**Comment by wooferzfg** [comment]
One possibility is that the updater downloaded the new Racetime file, but didn't download the latest LiveSplit.Core.dll file due to some caching of the network request to GitHub. That kind of situation is too difficult for the auto updater to deal with, unfortunately.

**Comment by wooferzfg** [comment]
When I tried running 1.8.29 but copied `LiveSplit.Core.dll`, `LiveSplit.Core.dll.config`, and `LiveSplit.View.dll` from 1.8.28, I got the same Racetime error. So it seems likely that the auto updater is only updating some of the files.

**Comment by wooferzfg** [comment]
A [user who was having this issue](https://x.com/datlossit/status/1789575891867074562) sent me their build, and it looks like none of the files in the main update (anything in `https://livesplit.org/update/update.xml`) were updated, even though every component was updated.
