### ISSUE TITLE
Autosplitter issues

### ISSUE THREAD

**Issue by DankDread** [LiveSplit/LiveSplit#2506]
Hey guys, I have been playing It Takes Two and doing Inbounds runs using the autosplitter. I haven't used the autosplitter in a while, but after reactivating it it seems to not work no matter what I do. I can allow full access to the folder Livesplit is in, I did a clean install of Windows 11 Pro, and have tried multiple things from multiple forums. I am currently getting the following error code in the Event Viewer
"The handle is invalid

   at LiveSplit.ComponentUtil.ExtensionMethods.ModulesWow64Safe(Process p)
   at LiveSplit.ComponentUtil.DeepPointer.DerefOffsets(Process process, IntPtr& ptr)
   at LiveSplit.ComponentUtil.DeepPointer.DerefString(Process process, ReadStringType type, StringBuilder sb)
   at LiveSplit.ASL.ASLState.GetValue(Process p, String type, DeepPointer pointer)
   at LiveSplit.ASL.ASLState.RefreshValues(Process p)
   at LiveSplit.ASL.ASLScript.DoUpdate(LiveSplitState state)
   at LiveSplit.UI.Components.ASLComponent.UpdateScript()"
I have tried using the newest version of Livesplit all the way down to 1.8.26 and I am stumped. I was previously getting an error for read / write to the memory, and it seems to not be happening anymore? I have fully disabled windows defender to make sure it isn't causing an issue and still no luck. Let me know if you need anymore information and I will gladly give it to you. Thanks

**Comment by wooferzfg** [comment]
Please reach out to the developer directly (@Lemuura), or make an issue on their repository https://github.com/Lemuura/It-Takes-Two-Autosplitter
