### ISSUE TITLE
Sometimes after run is finished can't save splits

### ISSUE THREAD

**Issue by partoftheworlD** [LiveSplit/LiveSplit#2523]
![image](https://github.com/user-attachments/assets/31a8d8d6-335e-42c0-a891-05989f575064)

System.Net.WebException: Operation timeout
```
   at SpeedrunComSharp.SpeedrunComClient.DoRequest(Uri uri)
   at SpeedrunComSharp.SpeedrunComClient.DoDataCollectionRequest[T](Uri uri, Func`2 parser)
   at SpeedrunComSharp.GamesClient.GetVariables(String gameId, VariablesOrdering orderBy)
   at System.Lazy`1.CreateValue()
---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Lazy`1.get_Value()
   at SpeedrunComSharp.Game.get_FullGameVariables()
   at LiveSplit.Model.RunExtensions.GetExtendedCategoryName(IRun run, Boolean showRegion, Boolean showPlatform, Boolean showVariables, Boolean waitForOnlineData)
   at LiveSplit.Model.RunExtensions.GetExtendedName(IRun run, Boolean useExtendedCategoryName)
   at LiveSplit.Model.RunExtensions.GetExtendedFileName(IRun run, Boolean useExtendedCategoryName)
   at LiveSplit.View.TimerForm.SaveSplitsAs(Boolean promptPBMessage)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
   ```

**Comment by wooferzfg** [comment]
Can you send your splits file?

**Comment by partoftheworlD** [comment]
[Split](https://raw.githubusercontent.com/partoftheworlD/Splits/master/Alan%20Wake%20-%20Ep%206.lss)

**Comment by wooferzfg** [comment]
@partoftheworlD That link is giving me a 404

**Comment by wooferzfg** [comment]
This is happening due to requests to Speedrun.com timing out. We should probably catch the error and show some other file name instead

**Comment by partoftheworlD** [comment]
@wooferzfg Looks like the splits file has been updated from last link. Can I disable sending a request to speedrun.com? 
[Alan Wake - Ep 6.zip](https://github.com/user-attachments/files/16683619/Alan.Wake.-.Ep.6.zip)

**Comment by wooferzfg** [comment]
You could block LiveSplit's connection to the internet with your firewall settings

**Comment by partoftheworlD** [comment]
Got it, thanks.
