### ISSUE TITLE
Live Split Not Opening

### ISSUE THREAD

**Issue by AidanFitzpatrick17** [LiveSplit/LiveSplit#2546]
Ive looked around for about an hour now and found nothing that works for me, it isnt opening but is showing in my task manager (as seen in the gyazo link below). Im really unsure on what to do especially with this error that is show in the windows application logs

```
Cannot delete a subkey tree because the subkey does not exist.

   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at Microsoft.Win32.RegistryKey.DeleteSubKeyTree(String subkey, Boolean throwOnMissingSubKey)
   at LiveSplit.Options.FiletypeRegistryHelper.RegisterFileFormats()
```

ive tried reinstalling and installing older builds/recent dev build aswell im unsure on what to do

https://gyazo.com/34e6a6a5d82803df0b8eda28cad5b5bb

**Comment by GMPranav** [comment]
In my experience, this is usually a matter of livesplit not being able to make network requests for whatever reason (Firewall, IP blocking, etc.)

Can you share the logs (if any) in [dbgview](https://learn.microsoft.com/en-us/sysinternals/downloads/debugview) that shows up when you open livesplit?

**Comment by wooferzfg** [comment]
@AidanFitzpatrick17 You might need to dig into the Windows registry to clean up the keys there. Alternatively, could you try saying "no" when LiveSplit asks for permissions on startup?
