### ISSUE TITLE
LiveSplit crashing on finished run due to Noesis.JavaScript.dll component

### ISSUE THREAD

**Issue by skateman222** [LiveSplit/LiveSplit#904]
Hi LiveSplit team,

I have been having this issue lately with LiveSplit where when I finish one of my first attempts of a new splits file, this error pops up and crashes LiveSplit:

Could not load file or assembly '[my LiveSplit path]\Components\Noesis.Javascript.dll' or one of its dependencies. An attempt was made to load a program with an incorrect format.

   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadFrom(String assemblyFile, Evidence securityEvidence, Byte[] hashValue, AssemblyHashAlgorithm hashAlgorithm, Boolean forIntrospection, Boolean suppressSecurityChecks, StackCrawlMark& stackMark)
   at System.Reflection.Assembly.UnsafeLoadFrom(String assemblyFile)
   at LiveSplit.UI.Components.ComponentManager.LoadFactory(String path)

Not sure what the Noesis.Javascript component is used for, so if you know what could be going, please help me out whenever you can. Let me know if you need any more information as well to assess my issue better.

Thanks!

**Comment by wooferzfg** [comment]
Are you using some kind of non-standard component? LoadFactory is only called when LS starts or when downloading new files for an AutoSplitter, and both are in a try catch block.

**Comment by skateman222** [comment]
I figured it might've been the non-standard component. I made a change to an existing component myself, which has worked for my existing split files, but not newer ones. So, maybe there's a problem on my end. However, I tried removing everything on my splits layout that wasn't the splits, timer and title and it would still crash with the same error. Would it still crash with it simply being in my Components folder? I am also using an autosplitter that's auto-fetched by LiveSplit (this is my first time trying this method of autosplitter with A Hat in Time).

**Comment by skateman222** [comment]
Oh, I just reread your comment; LoadFactory gets called when LiveSplit _starts_. So I'd have to remove it from the layout, save it, then reload LiveSplit maybe?

**Comment by wooferzfg** [comment]
You might want to just redownload LiveSplit, extract it to a different directory, run it from there, and see if you still have the issue.

**Comment by skateman222** [comment]
Yeah, that would most likely fix it for sure. Just didn't wanna go through that hassle. At least I know what causes it and can play around knowing this information.

Thanks for the speedy response, wooferzfg! Feel free to close/delete this non-issue.
